[package]
name = "lr_parser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
macros = { path = "macros" }
common = { path = "common" }
regex = "*"

[[example]]
name = "calculator"